### PR TITLE
Created it.md with the Italian help translation

### PR DESCRIPTION
**Pull request by giorgiogamberini**
First version for the Italian help markdown, fixes based on my app translations will follow if need be.

### CODE REVIEW

**Comment by alexanderby** [comment]
That's super, thanks. I will publish it soon.

**Comment by giorgiogamberini** [comment]
Sorry @alexanderby just noticed I missed the alt tags!

**Comment by alexanderby** [comment]
It's not so important. I've pushed the update 4.6.4, usually it takes up to 30 minutes for Chrome, and 5 minutes for Firefox. So now new Italian users will see your translation.

**Comment by giorgiogamberini** [comment]
That's great, thanks @alexanderby, I'm happy to help ;)

**Pull request merged**
