### PR TITLE
Add zh_TW.md

### PR DESCRIPTION
**Pull request by reiscigit**
This is the Traditional Chinese translation (zh-TW) for the Help page.

### CODE REVIEW

**Comment by alexanderby** [comment]
@reiscigit How do you think, would it be helpful for those, who use Chinese Simplified? If it could be useful, could you please rename the file to `zh.md`? If not, could you please right-click Dark Reader icon, select "Inspect Popup", and run `chrome.i18n.getUILanguage()` in Console? This will give a proper file name. Most likely it will be `zh-TW`, without the underscore.

**Comment by alexanderby** [comment]
The reason for this confusion is that Chrome extensions use locale files names with underscores. I've just renamed the sources to use dashes.

**Comment by reiscigit** [comment]
Hi, @alexanderby
Sorry I misspelled the filename. It is better to separate the Simplified and Traditional Chinese. I should add the zh-CN.md for the Help page soon.

i118n

**Comment by alexanderby** [comment]
Great, thanks, I will publish it soon.

**Pull request merged**
