### PR TITLE
Add pt-BR.md

### PR DESCRIPTION
**Pull request by FaelLiberatori**
Add Brazilian Portuguese translation for the help page.

### CODE REVIEW

**Comment by alexanderby** [comment]
Sorry, didn't notice it.

How do you think, is it applicable to pt-PT? Maybe let's rename to `pt.md`?

**Comment by FaelLiberatori** [comment]
> Sorry, didn't notice it.
> 
> How do you think, is it applicable to pt-PT? Maybe let's rename to `pt.md`?

The difference is pretty much the same as American English vs British English. Some words are different, the accent is different, but we can understand each other with no problem. Ideally, it should have pt-PT and pt-BR, but, as far as we have no pt-PT yet, I see no problem renaming it to pt.md.

Do I rename it or do you rename it?

**Comment by alexanderby** [comment]
Great. The app translation for PT and BR is the same either. I think you should do it, so that your name will remain in Dark Reader's git history :)

**Comment by FaelLiberatori** [comment]
Done.

**Comment by alexanderby** [comment]
Thank you. Sorry for the delay, I'm receiving too much notifications now. Just published on the website.

I will add a reference to the available translation in the app soon. Now both Chrome and Firefox teams do manual code check for every update.

**Pull request merged**
